#Functions in a file

f=open("Sample.txt","w")
print(f.writable())
f=open("Sample.txt","w")
f.write("Hello Everyone!\n")
f=open("Sample.txt","a")
f.writelines(["This program has been created by Rajat Sharma\n","I tried writelines function\n","Hope you like me programming"])
f=open("Sample.txt","r")
f.detach()
f=open("Sample.txt","r")
print(f.fileno())
# f=open("Sample.txt","r")
print(f.flush())
# f=open("Sample.txt","r")
print(f.isatty())
# f=open("Sample.txt","r")
print(f.read())
# f=open("Sample.txt","r")
print(f.readable())
f=open("Sample.txt","r")
print(f.readline(2))
f=open("Sample.txt","r")
print(f.readlines(1))
# f=open("Sample.txt","r")
print(f.seekable())
# f=open("Sample.txt","r")
f.seek(2)
# f=open("Sample.txt","r")
print(f.tell())
f=open("Sample.txt","w")
f.truncate(10)
f.close()
f=open("Sample.txt","r")
print(f.read())